apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database
  namespace: steward-postgres
  labels:
    app.kubernetes.io/name: database
    app.kubernetes.io/part-of: steward
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: px-csi-db-repl2
  resources:
    requests:
      storage: 8Gi
