apiVersion: v1
kind: Service
metadata:
  name: database
  namespace: steward-postgres
  labels:
    app.kubernetes.io/name: database
    app.kubernetes.io/component: postgresql
    app.kubernetes.io/part-of: steward
spec:
  selector:
    app.kubernetes.io/name: database
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  type: ClusterIP
