apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: steward-pacman
  namespace: openshift-gitops
spec:
  description: Pac-Man application namespace
  sourceRepos:
    - https://github.com/joelapatatechaude/test-ns-steward.git
  destinations:
    - namespace: steward-pacman
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ''
      kind: Namespace
